# Really small model on BTEC for debugging purposes

dropout_rate: 0.0     # 0.5
cell_size: 512
attn_size: 512
embedding_size: 256   # 512

layers: 1
bidir: True
use_lstm: False
steps_per_checkpoint: 500
steps_per_eval: 1000
eval_burn_in: 0
max_steps: 80000
max_output_len: 25
max_input_len: 25
feed_previous: 0.0

data_dir: data/btec
model_dir: models/debug_adam
log_file: models/debug_adam/log.txt
max_dev_size: 0
batch_size: 32
read_ahead: 10

optimizer: 'adam'
weight_scale: 0.01
max_gradient_norm: 1.0

encoders:
  - name: fr

decoder:
    name: en
